apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: promtail-monitor
  labels:
    #This label, which is applied to the PodMonitor is essential for allow Prometheus to discover this PodMonitor
    release: my-prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail # Select pods with this label
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: http-metrics # The name of the port in the pod
      path: /metrics      # The path where metrics are exposed